# encoding: utf-8
# Autogenerated by the db:seed:dump task
# Do not hesitate to tweak this to your needs

Category.create([
  { :category_name => "Computer Science" },
  { :category_name => "Chemistry" },
  { :category_name => "Architecture" }
], :without_protection => true )



Country.create([
  { :country_id => "AF", :country_name => "AFGHANISTAN" },
  { :country_id => "AX", :country_name => "ÅLAND ISLANDS" },
  { :country_id => "AL", :country_name => "ALBANIA" },
  { :country_id => "DZ", :country_name => "ALGERIA" },
  { :country_id => "AS", :country_name => "AMERICAN SAMOA" },
  { :country_id => "AD", :country_name => "ANDORRA" },
  { :country_id => "AO", :country_name => "ANGOLA" },
  { :country_id => "AI", :country_name => "ANGUILLA" },
  { :country_id => "AQ", :country_name => "ANTARCTICA" },
  { :country_id => "AG", :country_name => "ANTIGUA AND BARBUDA" },
  { :country_id => "AR", :country_name => "ARGENTINA" },
  { :country_id => "AM", :country_name => "ARMENIA" },
  { :country_id => "AW", :country_name => "ARUBA" },
  { :country_id => "AU", :country_name => "AUSTRALIA" },
  { :country_id => "AT", :country_name => "AUSTRIA" },
  { :country_id => "AZ", :country_name => "AZERBAIJAN" },
  { :country_id => "BS", :country_name => "BAHAMAS" },
  { :country_id => "BH", :country_name => "BAHRAIN" },
  { :country_id => "BD", :country_name => "BANGLADESH" },
  { :country_id => "BB", :country_name => "BARBADOS" },
  { :country_id => "BY", :country_name => "BELARUS" },
  { :country_id => "BE", :country_name => "BELGIUM" },
  { :country_id => "BZ", :country_name => "BELIZE" },
  { :country_id => "BJ", :country_name => "BENIN" },
  { :country_id => "BM", :country_name => "BERMUDA" },
  { :country_id => "BT", :country_name => "BHUTAN" },
  { :country_id => "BO", :country_name => "BOLIVIA, PLURINATIONAL STATE OF" },
  { :country_id => "BQ", :country_name => "BONAIRE, SINT EUSTATIUS AND SABA" },
  { :country_id => "BA", :country_name => "BOSNIA AND HERZEGOVINA" },
  { :country_id => "BW", :country_name => "BOTSWANA" },
  { :country_id => "BV", :country_name => "BOUVET ISLAND" },
  { :country_id => "BR", :country_name => "BRAZIL" },
  { :country_id => "IO", :country_name => "BRITISH INDIAN OCEAN TERRITORY" },
  { :country_id => "BN", :country_name => "BRUNEI DARUSSALAM" },
  { :country_id => "BG", :country_name => "BULGARIA" },
  { :country_id => "BF", :country_name => "BURKINA FASO" },
  { :country_id => "BI", :country_name => "BURUNDI" },
  { :country_id => "KH", :country_name => "CAMBODIA" },
  { :country_id => "CM", :country_name => "CAMEROON" },
  { :country_id => "CA", :country_name => "CANADA" },
  { :country_id => "CV", :country_name => "CAPE VERDE" },
  { :country_id => "KY", :country_name => "CAYMAN ISLANDS" },
  { :country_id => "CF", :country_name => "CENTRAL AFRICAN REPUBLIC" },
  { :country_id => "TD", :country_name => "CHAD" },
  { :country_id => "CL", :country_name => "CHILE" },
  { :country_id => "CN", :country_name => "CHINA" },
  { :country_id => "CX", :country_name => "CHRISTMAS ISLAND" },
  { :country_id => "CC", :country_name => "COCOS (KEELING) ISLANDS" },
  { :country_id => "CO", :country_name => "COLOMBIA" },
  { :country_id => "KM", :country_name => "COMOROS" },
  { :country_id => "CG", :country_name => "CONGO" },
  { :country_id => "CD", :country_name => "CONGO, THE DEMOCRATIC REPUBLIC OF THE" },
  { :country_id => "CK", :country_name => "COOK ISLANDS" },
  { :country_id => "CR", :country_name => "COSTA RICA" },
  { :country_id => "CI", :country_name => "CÔTE D'IVOIRE" },
  { :country_id => "HR", :country_name => "CROATIA" },
  { :country_id => "CU", :country_name => "CUBA" },
  { :country_id => "CW", :country_name => "CURAÇAO" },
  { :country_id => "CY", :country_name => "CYPRUS" },
  { :country_id => "CZ", :country_name => "CZECH REPUBLIC" },
  { :country_id => "DK", :country_name => "DENMARK" },
  { :country_id => "DJ", :country_name => "DJIBOUTI" },
  { :country_id => "DM", :country_name => "DOMINICA" },
  { :country_id => "DO", :country_name => "DOMINICAN REPUBLIC" },
  { :country_id => "EC", :country_name => "ECUADOR" },
  { :country_id => "EG", :country_name => "EGYPT" },
  { :country_id => "SV", :country_name => "EL SALVADOR" },
  { :country_id => "GQ", :country_name => "EQUATORIAL GUINEA" },
  { :country_id => "ER", :country_name => "ERITREA" },
  { :country_id => "EE", :country_name => "ESTONIA" },
  { :country_id => "ET", :country_name => "ETHIOPIA" },
  { :country_id => "FK", :country_name => "FALKLAND ISLANDS (MALVINAS)" },
  { :country_id => "FO", :country_name => "FAROE ISLANDS" },
  { :country_id => "FJ", :country_name => "FIJI" },
  { :country_id => "FI", :country_name => "FINLAND" },
  { :country_id => "FR", :country_name => "FRANCE" },
  { :country_id => "GF", :country_name => "FRENCH GUIANA" },
  { :country_id => "PF", :country_name => "FRENCH POLYNESIA" },
  { :country_id => "TF", :country_name => "FRENCH SOUTHERN TERRITORIES" },
  { :country_id => "GA", :country_name => "GABON" },
  { :country_id => "GM", :country_name => "GAMBIA" },
  { :country_id => "GE", :country_name => "GEORGIA" },
  { :country_id => "DE", :country_name => "GERMANY" },
  { :country_id => "GH", :country_name => "GHANA" },
  { :country_id => "GI", :country_name => "GIBRALTAR" },
  { :country_id => "GR", :country_name => "GREECE" },
  { :country_id => "GL", :country_name => "GREENLAND" },
  { :country_id => "GD", :country_name => "GRENADA" },
  { :country_id => "GP", :country_name => "GUADELOUPE" },
  { :country_id => "GU", :country_name => "GUAM" },
  { :country_id => "GT", :country_name => "GUATEMALA" },
  { :country_id => "GG", :country_name => "GUERNSEY" },
  { :country_id => "GN", :country_name => "GUINEA" },
  { :country_id => "GW", :country_name => "GUINEA-BISSAU" },
  { :country_id => "GY", :country_name => "GUYANA" },
  { :country_id => "HT", :country_name => "HAITI" },
  { :country_id => "HM", :country_name => "HEARD ISLAND AND MCDONALD ISLANDS" },
  { :country_id => "VA", :country_name => "HOLY SEE (VATICAN CITY STATE)" },
  { :country_id => "HN", :country_name => "HONDURAS" },
  { :country_id => "HK", :country_name => "HONG KONG" },
  { :country_id => "HU", :country_name => "HUNGARY" },
  { :country_id => "IS", :country_name => "ICELAND" },
  { :country_id => "IN", :country_name => "INDIA" },
  { :country_id => "ID", :country_name => "INDONESIA" },
  { :country_id => "IR", :country_name => "IRAN, ISLAMIC REPUBLIC OF" },
  { :country_id => "IQ", :country_name => "IRAQ" },
  { :country_id => "IE", :country_name => "IRELAND" },
  { :country_id => "IM", :country_name => "ISLE OF MAN" },
  { :country_id => "IL", :country_name => "ISRAEL" },
  { :country_id => "IT", :country_name => "ITALY" },
  { :country_id => "JM", :country_name => "JAMAICA" },
  { :country_id => "JP", :country_name => "JAPAN" },
  { :country_id => "JE", :country_name => "JERSEY" },
  { :country_id => "JO", :country_name => "JORDAN" },
  { :country_id => "KZ", :country_name => "KAZAKHSTAN" },
  { :country_id => "KE", :country_name => "KENYA" },
  { :country_id => "KI", :country_name => "KIRIBATI" },
  { :country_id => "KP", :country_name => "KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF" },
  { :country_id => "KR", :country_name => "KOREA, REPUBLIC OF" },
  { :country_id => "KW", :country_name => "KUWAIT" },
  { :country_id => "KG", :country_name => "KYRGYZSTAN" },
  { :country_id => "LA", :country_name => "LAO PEOPLE'S DEMOCRATIC REPUBLIC" },
  { :country_id => "LV", :country_name => "LATVIA" },
  { :country_id => "LB", :country_name => "LEBANON" },
  { :country_id => "LS", :country_name => "LESOTHO" },
  { :country_id => "LR", :country_name => "LIBERIA" },
  { :country_id => "LY", :country_name => "LIBYA" },
  { :country_id => "LI", :country_name => "LIECHTENSTEIN" },
  { :country_id => "LT", :country_name => "LITHUANIA" },
  { :country_id => "LU", :country_name => "LUXEMBOURG" },
  { :country_id => "MO", :country_name => "MACAO" },
  { :country_id => "MK", :country_name => "MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF" },
  { :country_id => "MG", :country_name => "MADAGASCAR" },
  { :country_id => "MW", :country_name => "MALAWI" },
  { :country_id => "MY", :country_name => "MALAYSIA" },
  { :country_id => "MV", :country_name => "MALDIVES" },
  { :country_id => "ML", :country_name => "MALI" },
  { :country_id => "MT", :country_name => "MALTA" },
  { :country_id => "MH", :country_name => "MARSHALL ISLANDS" },
  { :country_id => "MQ", :country_name => "MARTINIQUE" },
  { :country_id => "MR", :country_name => "MAURITANIA" },
  { :country_id => "MU", :country_name => "MAURITIUS" },
  { :country_id => "YT", :country_name => "MAYOTTE" },
  { :country_id => "MX", :country_name => "MEXICO" },
  { :country_id => "FM", :country_name => "MICRONESIA, FEDERATED STATES OF" },
  { :country_id => "MD", :country_name => "MOLDOVA, REPUBLIC OF" },
  { :country_id => "MC", :country_name => "MONACO" },
  { :country_id => "MN", :country_name => "MONGOLIA" },
  { :country_id => "ME", :country_name => "MONTENEGRO" },
  { :country_id => "MS", :country_name => "MONTSERRAT" },
  { :country_id => "MA", :country_name => "MOROCCO" },
  { :country_id => "MZ", :country_name => "MOZAMBIQUE" },
  { :country_id => "MM", :country_name => "MYANMAR" },
  { :country_id => "NA", :country_name => "NAMIBIA" },
  { :country_id => "NR", :country_name => "NAURU" },
  { :country_id => "NP", :country_name => "NEPAL" },
  { :country_id => "NL", :country_name => "NETHERLANDS" },
  { :country_id => "NC", :country_name => "NEW CALEDONIA" },
  { :country_id => "NZ", :country_name => "NEW ZEALAND" },
  { :country_id => "NI", :country_name => "NICARAGUA" },
  { :country_id => "NE", :country_name => "NIGER" },
  { :country_id => "NG", :country_name => "NIGERIA" },
  { :country_id => "NU", :country_name => "NIUE" },
  { :country_id => "NF", :country_name => "NORFOLK ISLAND" },
  { :country_id => "MP", :country_name => "NORTHERN MARIANA ISLANDS" },
  { :country_id => "NO", :country_name => "NORWAY" },
  { :country_id => "OM", :country_name => "OMAN" },
  { :country_id => "PK", :country_name => "PAKISTAN" },
  { :country_id => "PW", :country_name => "PALAU" },
  { :country_id => "PS", :country_name => "PALESTINE, STATE OF" },
  { :country_id => "PA", :country_name => "PANAMA" },
  { :country_id => "PG", :country_name => "PAPUA NEW GUINEA" },
  { :country_id => "PY", :country_name => "PARAGUAY" },
  { :country_id => "PE", :country_name => "PERU" },
  { :country_id => "PH", :country_name => "PHILIPPINES" },
  { :country_id => "PN", :country_name => "PITCAIRN" },
  { :country_id => "PL", :country_name => "POLAND" },
  { :country_id => "PT", :country_name => "PORTUGAL" },
  { :country_id => "PR", :country_name => "PUERTO RICO" },
  { :country_id => "QA", :country_name => "QATAR" },
  { :country_id => "RE", :country_name => "RÉUNION" },
  { :country_id => "RO", :country_name => "ROMANIA" },
  { :country_id => "RU", :country_name => "RUSSIAN FEDERATION" },
  { :country_id => "RW", :country_name => "RWANDA" },
  { :country_id => "BL", :country_name => "SAINT BARTHÉLEMY" },
  { :country_id => "SH", :country_name => "SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA" },
  { :country_id => "KN", :country_name => "SAINT KITTS AND NEVIS" },
  { :country_id => "LC", :country_name => "SAINT LUCIA" },
  { :country_id => "MF", :country_name => "SAINT MARTIN (FRENCH PART)" },
  { :country_id => "PM", :country_name => "SAINT PIERRE AND MIQUELON" },
  { :country_id => "VC", :country_name => "SAINT VINCENT AND THE GRENADINES" },
  { :country_id => "WS", :country_name => "SAMOA" },
  { :country_id => "SM", :country_name => "SAN MARINO" },
  { :country_id => "ST", :country_name => "SAO TOME AND PRINCIPE" },
  { :country_id => "SA", :country_name => "SAUDI ARABIA" },
  { :country_id => "SN", :country_name => "SENEGAL" },
  { :country_id => "RS", :country_name => "SERBIA" },
  { :country_id => "SC", :country_name => "SEYCHELLES" },
  { :country_id => "SL", :country_name => "SIERRA LEONE" },
  { :country_id => "SG", :country_name => "SINGAPORE" },
  { :country_id => "SX", :country_name => "SINT MAARTEN (DUTCH PART)" },
  { :country_id => "SK", :country_name => "SLOVAKIA" },
  { :country_id => "SI", :country_name => "SLOVENIA" },
  { :country_id => "SB", :country_name => "SOLOMON ISLANDS" },
  { :country_id => "SO", :country_name => "SOMALIA" },
  { :country_id => "ZA", :country_name => "SOUTH AFRICA" },
  { :country_id => "GS", :country_name => "SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS" },
  { :country_id => "SS", :country_name => "SOUTH SUDAN" },
  { :country_id => "ES", :country_name => "SPAIN" },
  { :country_id => "LK", :country_name => "SRI LANKA" },
  { :country_id => "SD", :country_name => "SUDAN" },
  { :country_id => "SR", :country_name => "SURINAME" },
  { :country_id => "SJ", :country_name => "SVALBARD AND JAN MAYEN" },
  { :country_id => "SZ", :country_name => "SWAZILAND" },
  { :country_id => "SE", :country_name => "SWEDEN" },
  { :country_id => "CH", :country_name => "SWITZERLAND" },
  { :country_id => "SY", :country_name => "SYRIAN ARAB REPUBLIC" },
  { :country_id => "TW", :country_name => "TAIWAN, PROVINCE OF CHINA" },
  { :country_id => "TJ", :country_name => "TAJIKISTAN" },
  { :country_id => "TZ", :country_name => "TANZANIA, UNITED REPUBLIC OF" },
  { :country_id => "TH", :country_name => "THAILAND" },
  { :country_id => "TL", :country_name => "TIMOR-LESTE" },
  { :country_id => "TG", :country_name => "TOGO" },
  { :country_id => "TK", :country_name => "TOKELAU" },
  { :country_id => "TO", :country_name => "TONGA" },
  { :country_id => "TT", :country_name => "TRINIDAD AND TOBAGO" },
  { :country_id => "TN", :country_name => "TUNISIA" },
  { :country_id => "TR", :country_name => "TURKEY" },
  { :country_id => "TM", :country_name => "TURKMENISTAN" },
  { :country_id => "TC", :country_name => "TURKS AND CAICOS ISLANDS" },
  { :country_id => "TV", :country_name => "TUVALU" },
  { :country_id => "UG", :country_name => "UGANDA" },
  { :country_id => "UA", :country_name => "UKRAINE" },
  { :country_id => "AE", :country_name => "UNITED ARAB EMIRATES" },
  { :country_id => "GB", :country_name => "UNITED KINGDOM" },
  { :country_id => "US", :country_name => "UNITED STATES" },
  { :country_id => "UM", :country_name => "UNITED STATES MINOR OUTLYING ISLANDS" },
  { :country_id => "UY", :country_name => "URUGUAY" },
  { :country_id => "UZ", :country_name => "UZBEKISTAN" },
  { :country_id => "VU", :country_name => "VANUATU" },
  { :country_id => "VE", :country_name => "VENEZUELA, BOLIVARIAN REPUBLIC OF" },
  { :country_id => "VN", :country_name => "VIET NAM" },
  { :country_id => "VG", :country_name => "VIRGIN ISLANDS, BRITISH" },
  { :country_id => "VI", :country_name => "VIRGIN ISLANDS, U.S." },
  { :country_id => "WF", :country_name => "WALLIS AND FUTUNA" },
  { :country_id => "EH", :country_name => "WESTERN SAHARA" },
  { :country_id => "YE", :country_name => "YEMEN" },
  { :country_id => "ZM", :country_name => "ZAMBIA" },
  { :country_id => "ZW", :country_name => "ZIMBABWE" }
], :without_protection => true )

AdminPermission.create([
  { :permission_name => "Super Admin" },
  { :permission_name => "Admin"},
  { :permission_name => "Teacher"}
  ], :without_protection => true )

AdminUser.create([
  { :forename => "Test",
    :surname => "Admin",
    :email => 'admin@example.com',
    :password => 'password',
    :password_confirmation => 'password',
    :admin_permission_id => AdminPermission.first.id
  },
  { :forename => "Teacher",
    :surname => "Name",
    :email => 'teacher@example.com',
    :password => 'password',
    :password_confirmation => 'password',
    :admin_permission_id => AdminPermission.last.id
  },
], :without_protection => true )

Teacher.create([
    {
      :is_active => true, :description => Faker::Lorem.paragraph(10), :admin_user_id => AdminUser.last.id
    }
  ])

Course.create([
  { :title => "Intro to programming",
    :description => Faker::Lorem.paragraph(10),
    :brief_description => Faker::Lorem.sentence(10),
    :teacher_id => Teacher.first.id,
    :number_of_places => 50,
    :price => 100.0,
    :deposit => 10.0, :category_id => Category.first.id, :hits => 0 },
  { :title => "Some course",
    :description => "full description",
    :brief_description => "brief description",
    :teacher_id => Teacher.first.id,
    :number_of_places => 50,
    :price => 100.0,
    :deposit => 10.0,
    :category_id => Category.first.id,
    :hits => 0 }
], :without_protection => true )

Sex.create([
  { :sex_id => 0, :sex_name => "not known" },
  { :sex_id => 1, :sex_name => "male" },
  { :sex_id => 2, :sex_name => "female" },
  { :sex_id => 9, :sex_name => "not applicable" }
], :without_protection => true )

MessageThread.create([
  { id: SecureRandom.urlsafe_base64(6),
    user_email: "test@test.com",
    :subject => "test subject"
  }
], :without_protection => true )

Message.create([
  { :message_thread_id => MessageThread.first.id,
    :is_response => false,
    :content => "test message",
}
], :without_protection => true )

Student.create([
  { email: "jtreanor3@gmail.com", forename: "James", surname: "Treanor", password: "password", password_confirmation: "password", year_of_birth: 1991, country_id: "IE", sex_id: 1
    }])
s = Student.first
s.confirmed_at = DateTime.now
s.save

Location.create([
    { title: 'Western Gateway', longitude: -8.492932, latitude: 51.892162}
                ])

Course.first.time_table_items.create(
    location_id: Location.first.id,
    start_time: DateTime.new(2013,9,9,15),
    end_time: DateTime.new(2013,9,9,16),
    room: 'G21'
)
Course.first.time_table_items.create(
    location_id: Location.first.id,
    start_time: DateTime.new(2013,9,10,10),
    end_time: DateTime.new(2013,9,10,12),
    room: '1.11'
)

Course.last.time_table_items.create(
    location_id: Location.first.id,
    start_time: DateTime.new(2013,10,9,15),
    end_time: DateTime.new(2013,10,9,16),
    room: 'G21'
)
Course.last.time_table_items.create(
    location_id: Location.first.id,
    start_time: DateTime.new(2013,10,10,10),
    end_time: DateTime.new(2013,10,10,12),
    room: '1.11'
)
=begin
Course.first.enrollments.create(
    student_id: Student.first.id
)
Image.create([
  { url: "http://www.youtube.com/watch?v=k6U-i4gXkLM&list=PL06458A6C3AAD892D&index=1", kind: "video", description: "test video description"
  },
  { url: "/assets/UCC-logo@2x.png", kind: "picture", description: "test picture description"
  }
])

CourseImage.create([
  { course_id: Course.first.id, 
    asset_id: Image.first.id
  },
  { course_id: Course.first.id,
    asset_id: Image.last.id
  }
])
=end
